[package]
name = "clitool"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "A CLI tool for classic ciphers"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0" 